### ISSUE TITLE
URLs with no segmentation parameter do not select "tokens" as segmentation

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#327]
At the moment, corpus.properties can set a segmentation other than tokens to be the default. This is then selected in the search options. When a query is executed, this default segmentation is coded in the URL. If the user changes base text to "tokens" the URL is updated to remove the segmentation parameter. 

Once this happens, or if the URL parameter for segmentations is deleted manually, and the user navigates again, the GUI does not use "tokens" as a segmentation, but takes the default segmentation from corpus.properties again. This means it is impossible to explicitly encode "tokens" as the selected base text in a citation URL instead of the corpus.properties setting.

**Comment by thomaskrause** [comment]
Since the version 3.4.0-preview5 there is the new "bt" citation URL parameter which encodes the "Base Text", which is the same as the one as selected in the menu manually. It is possible to have different "seg" and "bt" parametes and if the "bt" parameter is explicitly given but empty "tokens" are selected. As far as I understand the "bt" parameter should be a fix for this issue. Please re-open if not.
