### ISSUE TITLE
Can't set numbers=false and metakeys simultaneously in Grid exporter

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#392]
With the grid exporter, it's possible to set metakey parameters or numbers=false. Both should be usable at the same time using a semicolon separator:

numbers=false;metakeys=x,y,z

Currently both options work separately, but not at the same time using the ';' separator.

**Comment by thomaskrause** [comment]
The documentation here is unfortunately not complete: you have to use "&" as a separator and not ";". This is inconsistent with the resolver but historically grown since these parameters used to be part of a URL. We should definitely enhance the documentation and also evaluate if we want to use ";" as separator in the next release.

**Comment by amir-zeldes** [comment]
OK, if it’s been & for a while I think we should keep supporting it for backwards compatibility, but it wouldn’t hurt to add support for ; too for consistency. The user guide specifies semi-colon and this way we wouldn’t have to change it – just split by /;|&/

 

Does that sound OK?
