### ISSUE TITLE
Corpus and subcorpus metadata is not queryable

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#423]
It seems corpus and subcorpus metadata does not work in the 3.3 snapshot, and on korpling stable. Metadata annotating a DOCUMENT responds to queries, e.g. in a5.hausa.news:

```
tok & meta::date="13.05.2010"
```

1257 results

But CORPUS metadata does not:

```
tok & meta::language="Hausa"
```

0 results

I've also tested this with subcorpora: metadata assigned to a subcorpus is visualized in the corpus explorer and metadata window for each result, but querying it results in 0 hits.

**Comment by thomaskrause** [comment]
I tested this for old versions and neither in 2.2.1, 3.0.0 or any other later version this was implemented. We also state in our user guide, that

>we can add metadata restrictions to the query, which filter out documents not matching  our  definitions.

where we only documents are mentioned.

Technically this seems to be a feature request, but I also have to admit that this behaviour is unexpected. Especially if you search over several corpora this could be useful (or for defining subsets with sub-corpora). Since we don't promise it somewhere and no query using this could have worked in any old ANNIS version I still would see this as feature we should consider for the next 3.x release instead of creating a bugfix release for this issue.

**Comment by amir-zeldes** [comment]
It's all the same to me if it's a bug or enhancement, but I'm pretty sure users will be surprised if they see this behavior. I agree it's not urgent enough for a hotfix release, since nobody seems to have run into this problem before (probably because most formats don't naturally create subcorpora). But for subcorpora to be usable, this would be a useful feature (otherwise there's not much point to having subcorpora)

**Comment by amir-zeldes** [comment]
@thomaskrause OK, based on the discussion above I'm milestoning it for 3.4.0

**Comment by amir-zeldes** [comment]
I just ran into this issue again - I'd forgotten subcorpus metadata is not searchable, and I still find it very unexpected. I see it's not referenced in preview 3.5 - is this on track to be added to the 3.5 release?

**Comment by thomaskrause** [comment]
In graphANNIS AQL will probably get the new `@` operator. In its form `@*` it will allow querying annotations any any parent document/sub-corpus/corpus. Using a binary parametrized operator will allow select whether to include only the document/direct sub-corpus or any.

**Comment by amir-zeldes** [comment]
Interesting, can you give an example query for how this will work?

**Comment by thomaskrause** [comment]
This issue has been resolved in ANNIS 4.x with the new `@*` operator.

```
tok @* language="Hausa"
```

https://korpling.org/annis/#_q=dG9rIEAqIGxhbmd1YWdlPSJIYXVzYSI&ql=aql&_c=YTUuaGF1c2EubmV3cw&cl=5&cr=5&s=0&l=10
