### ISSUE TITLE
Escaping example_queries

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#515]
Example queries should be allowed to contain single quotes. Currently this query:

```
"au\'nni" . "lana"	Get all instances of the sequence "au\'nni lana"
```

Gets an error with and without backslash before the apostrophe. Ideally the importer should check for escaped and/or unescaped single quotes and fix the value as need for insertion.

**Comment by thomaskrause** [comment]
You should only need to esacpe tabstops or newlines here since the files are normal PostgreSQL import files in the "text format" (http://www.postgresql.org/docs/9.4/static/sql-copy.html#AEN72056). It seems that a later. So in theory
```
"au'nni" . "lana"	Get all instances of the sequence "au'nni lana"
```
should work. It seems that a later update statement in the import process (https://github.com/korpling/ANNIS/blob/master/annis-service/src/main/java/annis/administration/AdministrationDao.java#L2154) is improperly constructed and throws the error.
