### ISSUE TITLE
Or queries combined with meta fail

### ISSUE THREAD

**Issue by thomaskrause** [korpling/ANNIS#534]
Querying for meta annotation inside or clauses, like

```
tok & (meta::Titel="Steilpass" | meta::Titel="Feigenblatt")
```

is syntactically valid AQL but will not yield any results since the meta data filters are always combined as "AND". We have to either implement a correct OR behavior for meta data terms or syntactically disallow such queries.

@amir-zeldes What do you think about this issue?

**Comment by amir-zeldes** [comment]
I completely agree that the desired behavior is the disjunction, but I also recognize that this comes up fairly rarely (in fact, I've never had the opportunity to use this). For a single metadatum, you can easily use regex. So the more realistic scenario is two metadata keys. 

If it's a hassle to implement, then disallowing this makes sense, since the null result really is unexpected. Is there something that makes this particularly complicated? I don't think it's a high priority either way.

**Comment by thomaskrause** [comment]
Fixed in ANNIS 4 with the introduction of the `@*` operator, which arguments are normal annotation nodes an can be part of conjunctions and disjunctions. The old behavior is still available in compatibility mode and the restriction discussed in this issue has been [documented](http://korpling.github.io/ANNIS/4.0/user-guide/aql-compatibility-mode.html#meta-is-still-allowed).
