### ISSUE TITLE
API call for getting corpus or document names matching some metadata criteria

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#547]
It would be good to have an API call which returns the list of documents or corpora matching certain metadata criteria. Although we can get results for an AQL query containing metadata, it can have multiple hits per document. 

If I want the list of documents with `meta::author="Smith"` there is currently not simple way of doing so (it's possible to do `tok & meta::author="Smith"` and process the result for distinct documents, but this is clumsy and could produce large intermediate results). 

It would also be nice to be able to do this for corpora, as this will allow remote services to get information just from corpora belonging to some subset of interest, defined by common metadata.

**Comment by thomaskrause** [comment]
In ANNIS 4, you can search for meta data on corpus/subcorpus/document nodes the same way as any other annotation with a normal "find" API call. In the REST API, the corpus/subcorpus/document ID will be part of the match. The result view in the user interface will also attempt to show a sensible output (still buggy in 4.1.3, will be fixed in 4.1.4)

https://korpling.org/annis/#_q=dHlwZT0iY29udmVyc2F0aW9uIg&ql=aql&_c=R1VNLTcuMi4wbnI&cl=5&cr=5&s=0&l=10
