### ISSUE TITLE
Missing share button/link for individual resuls

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#626]
@thomaskrause The individual result share link (as described in #454 ) is missing from the UI in annis-gui, 4.0.0-beta.4-SNAPSHOT (rev. 6aca7828ec, built 2019-10-24 09:06:53). Was this removed on purpose or is it a bug/setting somewhere?

**Comment by ctschroeder** [comment]
Hello. I used this feature quite often in ANNIS 3 and am looking forward to learning whether it will be in the GUI for ANNIS 4. Thank you so much!

**Comment by thomaskrause** [comment]
This is still configurable, but compared to ANNIS 3 it is turned off by default. Set the `shorten-urls` property to `true` in the `annis-gui.properties` file. It will only be turned of per default in the beta version, since it was not clear if certain query operations like `@` would be implemented as they are right now. Does setting the configuration variable work for you?

**Comment by amir-zeldes** [comment]
I can set it at Georgetown, but I think the default should be on to match ANNIS3 behavior (and also to make new admins aware of the feature, since they might not look for it actively and miss knowing about it)

About `@`, I think because of the use of pasted queries in published papers (there are several for Scriptorium for example), it would be best to either turn on backwards compatibility with `meta::` by default, or else at least have some translation mechanism to intercept this when a URL contains a query with `meta::`

**Comment by ctschroeder** [comment]
Greetings!!

I wanted to chime in about the @ and meta:: compatibility question.  We have publications containing links to queries, such as the article in this volume: https://opr.degruyter.com/digital-humanities-and-research-methods-in-religious-studies/ <https://opr.degruyter.com/digital-humanities-and-research-methods-in-religious-studies/>, which was just released for open peer review.  If the meta:: query no longer functions, then the links will by default be dead.  Is it possible to maintain the meta:: option or at least continue compatibility with existing URLs? 

Thank you!

Best,
Carrie
______________________________
Caroline T. Schroeder, Ph.D.
carrie@carrieschroeder.com
www.carreschroeder.com
http://earlymonasticism.org/
https://copticscriptorium.org/

Professor, Classics and Letters
Core Affiliate Faculty, Women’s and Gender Studies
Data Scholarship Initiative
University of Oklahoma

**Comment by ctschroeder** [comment]
I wanted to re-up on the links and compatibility with the ANNIS4 syntax. Please let me know if I should start a new thread. 
All publications that used the meta:: syntax will now have dead links. We have a brand new publication appearing here https://opr.degruyter.com/digital-humanities-and-research-methods-in-religious-studies.  There are some other publications, as well, previously published or in the pipeline.
Is there any way to maintain backwards compatibility with the links using meta:: in the syntax?  Thank you!

**Comment by amir-zeldes** [comment]
@thomaskrause would it be possible to make auto conversion of meta:: to @* configurable in a properties file? Basically I think an OK behavior would be:

  * Whenever a term meta::([^\s]+) appears, remove it from the query and store it
  * Append @* $1 to the query (either in order of appearance, or alphabetic, etc., doesn't really matter)

Since ANNIS3 didn't really support a subcorpus/corpus/document meta distinction, I think this behavior would be reasonable and what users expect

**Comment by thomaskrause** [comment]
Hi, it is possible to import the existing reference queries (the shortened ones) from ANNIS 3 to 4: http://korpling.github.io/ANNIS/4.0/user-guide/installation-migrate-annis3.html#5-migrate-user-configuration-and-reference-links

This import will check all queries if they produce the same result in ANNIS 4 as in the previous version.
Whenever the result is different (as in the case of `meta::`), it will try the same query again in [compatibility mode](http://korpling.github.io/ANNIS/4.0/user-guide/aql-compatibility-mode.html).

The [compatibility mode still supports](http://korpling.github.io/ANNIS/4.0/user-guide/aql-compatibility-mode.html#meta-is-still-allowed) `meta::` in the original semantics.
If compatibility mode produces the same results, the shortened URL reference is rewritten to select this mode, e.g. like in this example:

https://korpling.org/annis-beta/#_q=dG9rICYgbWV0YTo6dHlwZT0iaW50ZXJ2aWV3Ig&ql=aql_quirks_v3&_c=R1VN&cl=5&cr=5&s=0&l=10

You can see in the search options, that the query was changed to this mode:
![image](https://user-images.githubusercontent.com/2168104/73646803-77ea0000-467a-11ea-858e-de4a7cd67300.png)

The URL reference link import will also report if a query was not possible to execute even in compatibility mode (e.g. because the corpus is missing). The administrator of the server can have a full overview of the status of the reference queries and can also choose to import problematic ones, that will be shown with a warning to the user that looks like this: 
https://korpling.org/annis-beta/unsupported-query?url=%23_q%3DdG9r%26ql%3Daql%26_c%3DR1VN%26cl%3D5%26cr%3D5%26s%3D0%26l%3D10

**Comment by ctschroeder** [comment]
Ok thank you, so if I understand this correctly, shortened URLs minted with the share buttons will be rewritten/converted using compatibility mode.  This is very helpful!! Thank you!
