### ISSUE TITLE
AQL request isn't working

### ISSUE THREAD

**Issue by Cesaaa** [korpling/ANNIS#646]
The corpora let's me validate my AQL query, but the loop doesn't stop spinning and it shows me no results.

**To Reproduce**
1. Go to 'AQL query and put i.e. '"vous" . POS="VRB" . POS="DET" . POS="NOM"'
2. Select the 'frantext' in the corpus list.
3. Click on 'Search'

**Expected behavior**
I expected to see results listed in the Query Results, but the loop doesn't stop spinning and it shows me no results. 

**Screenshots**

![Bildschirmfoto 2020-01-16 um 10 00 23](https://user-images.githubusercontent.com/59955622/72510459-c6f5ff80-3849-11ea-8b4e-305ce3a96939.png)

**Desktop (please complete the following information):**
 - Operating System: [iOS]
 - Browser [safari]

 - ANNIS Version [
![Bildschirmfoto 2020-01-16 um 10 19 15](https://user-images.githubusercontent.com/59955622/72510436-bcd40100-3849-11ea-8a3c-6cc590544f30.png)
]
 

**Additional context**
I Use the ANNIS Corpus Search via Website, I don't have the software installed on my Laptop.

**Comment by thomaskrause** [comment]
It seems like the query takes to long to execute on the server and produces a timeout. 

There can be various reasons why the query is to complex to execute in time. E.g. there could be a performance issue in the ANNIS software  or the server on which this ANNIS instance is running might not have enough power or needs a different configuration.
Since I don't have access to the corpus in the relANNIS format (I can download XML files from https://www.ortolang.fr/market/corpora/cefc-orfeo but not the converted data) and thus can't reproduce locally if there is something specifically wrong from the ANNIS software side. Since simpler queries like `"vous" . POS="VRB"` are running fine, there seems not to be a general issue with the server.

I contacted the project via their email orfeo@ens.fr if they can check their server for problems. Also, the version running on the server is quite old and the newer 3.6.0 version might perform better for this specific query. I don't know if the ORFEO project has any resources to update the ANNIS version on their server or if the project is already finished and in maintenance mode.

While we try to improve the ANNIS performance with every release to avoid timeouts,
I'm very sorry that I can't be of more help in this specific case. 
As the developer of ANNIS I don't have access or control of the various ANNIS server installations but can only fix issues in the software itself.
