### ISSUE TITLE
two constraints on the same token on one annotation level return empty results

### ISSUE THREAD

**Issue by otichy** [korpling/ANNIS#754]
I am not sure if this is a bug or a feature or if I am missing something, but when I do e.g.
```
pos=‎/PR.*‎/ & pos=‎/.*RO‎/
& #1 _=_ #2
```

I get no results. Similarly 

```
tok=‎"you" & tok="you"
& #1 _=_ #2
```

I know the examples are silly as such, but I would like to put two constraints on the same token e.g. with one positive and one negative constraint. All probably doable using a single complex regexp constraint, but more flexible and readable in multiple constraints. E.g. in CQL/CQP I can do:
`[word="y.*" & word!=.*t.*] `
for all tokens starting with <y> and not containing <t> and I was hoping that
```
tok=‎/y.*/ & tok!=/.*t.*/
& #1 _=_ #2
```
would do the same, but apparently not.
(Annis 3.6.0)

**Comment by MartinKl** [comment]
Hi @otichy,

this is actually not a bug. I think there's a slight misunderstanding in what the operators do.

In your first example, I assume you are looking for a part of speech-annotation that starts with "PR" and ends with "RO" and you prefer to express that on two terms rather than in one, as you stated. But the way your query is formulated, you are looking for two distinct annotations that overlap identically ("_=_"), i. e. with the same left and right boundary. But what you appear to have in mind (please correct if I am wrong) is the same annotation. As there is only one pos-annotation per token usually, you by definition get no results here. To keep it in your terms, you'd have to go for
```
pos=‎/PR.*‎/ & pos=‎/.*RO‎/
& #1 _ident_ #2
```
The nodes are identical, they do not have identical coverage (which requires the nodes to be distinct).

Same goes for your second example.

**Comment by otichy** [comment]
OK, I had a feeling I was missing something, thanks! 
I have to say this is the first time I have heard about the _ident_ operator. Since I am still at Annis 3.6, I was using this manual http://korpling.github.io/ANNIS/3.6/user-guide/aql-operators.html that does not list it, but I can see it in the list of operators for Annis 4.0 now.

**Comment by otichy** [comment]
Sorry to reopen, just wanted to add that the Query Builder (at least in 3.6) does not feature _ident_ and when you add more constraints inside the same node windows, the AQL uses _=_
E.g.
![image](https://user-images.githubusercontent.com/2981552/163164820-9eb1ebec-7c1c-41fc-89c1-6b9b1bd5ee6a.png)
gets translated as:
```
‎/y.*‎/ & tok!=‎/.*t.*‎/
& #1 _=_ #2
```
