### ISSUE TITLE
I can't import a corpus in annis server

### ISSUE THREAD

**Issue by evelinamorim** [korpling/ANNIS#809]
I downloaded the annis server 4.10.0 from[ https://corpus-tools.org/annis/download.html]( https://corpus-tools.org/annis/download.html), 
then I downloaded the subtok.demo corpus from [http://amir-zeldes.github.io/corpora.html](http://amir-zeldes.github.io/corpora.html). I executed the graphAnnis as detailed by [The Annis User Guide](http://korpling.github.io/ANNIS/4.1/user-guide/import-and-config/import.html) to import a corpus from the command line since the administration interface did not show up in my screen.

 After that, I loaded the annis server in a Ubuntu 20.04 using openjdk version "13.0.7". However, there is no corpus listed in the interface. What did go wrong? Why the admin interface is not showing up in my annis server?

**Comment by thomaskrause** [comment]
Can you check if the folder `~/.annis/v4/` has any subfolders? If the original import was successful, there should be a sub-folder with the name of the corpus.

Also, if you use the server version you might have not the rights to see the imported corpus on the server if you are not logged in. To allow all users without login to see all imported corpora, you can set a special configuration value in `~/.annis/service.toml`: 
http://korpling.github.io/ANNIS/4.10/user-guide/configuration/user.html#allowing-anonymous-access-to-all-corpora

Also there was in issue with the link to the user guide and it did point to an older version (4.1 instead of 4.10) on the website. The simplified `anonymous_access_all_corpora` setting has been added more recently.

**Comment by thomaskrause** [comment]
Closing this for now with the hope that the issue was indeed the authorization configuration and that that the `anonymous_access_all_corpora` helps in the situation.

Please re-open if the problem exists even with this configuration enabled.
