### ISSUE TITLE
Cannot import files in the subfolder of ExData in a corpora folder

### ISSUE THREAD

**Issue by fishfree** [korpling/ANNIS#822]
A example corpora can be downloaded `[here](https://codeload.github.com/CopticScriptorium/corpora/zip/refs/tags/v4.4.0)`. Because there are webfonts / css / other files in the ExData subfolder, all character get gibberish in the browser as the screenshot below:
![image](https://user-images.githubusercontent.com/1741341/236394086-6c7b0d73-8f5e-4988-9e0b-787ad0c5d4e8.png)

**Comment by thomaskrause** [comment]
The only example corpora we provide are linked from https://corpus-tools.org/annis/corpora.html
It seems like the link to  "abraham.our.father" and "apophthegmata.patrum.5" is broken, so I removed these links.

If you have a corpus that requires the use of web-fonts, you have to configure the the interface to use this web-font: <http://korpling.github.io/ANNIS/4.10/user-guide/configuration/instances.html#embedding-web-fonts>
This is not a per-corpus configuration, but per ANNIS instance and is by design.
