### ISSUE TITLE
Support interface language localization

### ISSUE THREAD

**Issue by fishfree** [korpling/ANNIS#823]
I found no way to translate the interface language, which is popular for Java applications.

**Comment by thomaskrause** [comment]
When we started development of ANNIS, we decided against supporting multiple interface languages. This feature not only needs to provide the actual translations, which is a huge overhead, especially for updating translations for languages the developers don't know, but also means that the internal architecture of the software needs to be made ready for providing such kind of translation. When you look e.g. at the [Project Fluent](https://projectfluent.org/) and their syntax for providing translations, you can see that this is not an easy task.

Since we develop ANNIS as part of a research project (or better said with minimal or no funding in several research projects) and ANNIS is meant as an interface for linguistic researchers, we decided against having to maintain this extra overhead.
