### ISSUE TITLE
Error (response code 401): "InvalidSignature"

### ISSUE THREAD

**Issue by nisathelinguist** [korpling/ANNIS#841]
Hello,

I got an error "Error (response code 401): "InvalidSignature"" when I tried to import a zip file to ANNIS.
The relevant screenshots are attached. 

I hope you can help me with this issue. 

![groceriesnotepad](https://github.com/korpling/ANNIS/assets/150890464/1eec5dc8-0585-41d6-b78a-61183fb7aa09)
![pepper](https://github.com/korpling/ANNIS/assets/150890464/49c3ffa5-a38c-44de-a67a-29194e80ed40)

![annis-tr-snapshot](https://github.com/korpling/ANNIS/assets/150890464/abade671-6a16-4b98-9144-67a1f2e7a69a)
![error401](https://github.com/korpling/ANNIS/assets/150890464/4e37638a-9f81-48d4-9558-b1bda9d636e4)
@MartinKl @thomaskrause

**Comment by MartinKl** [comment]
Hi,

if your corpus does not have any errors (who cannot be reported to you), it should be imported anyway. The error you're seeing just means that ANNIS' frontend cannot poll the import status from the backend due to an invalid authentication token, which is a bug that should have been fixed by now. Are you using the latest ANNIS Desktop?

Depending on the size of your corpus after some time you should find it in the corpus list.

**Comment by nisathelinguist** [comment]
@MartinKl Thanks a lot for your answer! It kept giving the same error for 2-3 days even though I used the final version of ANNIS. 
I don't know what has changed but when I tried it today, it worked.
