### ISSUE TITLE
Display of token count/query examples in Annis 4.11.3

### ISSUE THREAD

**Issue by gcelano** [korpling/ANNIS#858]
I cannot also see token count (i.e., size of the corpus) on the web interface. How can I solve this?

**Comment by thomaskrause** [comment]
This feature was only introduced in version 4.12.0 (<https://github.com/korpling/ANNIS/blob/main/CHANGELOG.md#4120---2024-05-29>) and is not available in ANNIS 4.11.3. 
To update ANNIS, you can simply stop the system service, replace the current jar file with the most recent one (
annis-4.12.2-server.jar) and restart the service 

You might need to re-import the corpus after updating ANNIS so that the correct token information is calculated during import.
